---
version: "3"

volumes:
  postgres:
  redis:

services:
  postgres:
    command: postgres -c max_connections=200 -c listen_addresses='*'
    environment:
      POSTGRES_USER: luminate
      POSTGRES_DATABASE: luminate
      POSTGRES_PASSWORD: luminate
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --appendonly yes